# playbook\04_seal-monitoring-auth-secret.yml
# ===============================================================
#   Crear y cifrar el Secret de autenticación básica para Prometheus y Grafana
# - Genera hash htpasswd
# - Renderiza el Secret plano
# - Lo cifra con kubeseal para uso en ArgoCD o GitOps seguro
# ===============================================================
---
- name: 🔐 Generar y cifrar Secret para Prometheus y Grafana
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/main.yml

  vars:
    kubeconfig_path: "/home/victory/.kube/config"
    kubeseal_path: "/usr/local/bin/kubeseal"
    kubectl_path: "/usr/local/bin/kubectl"
    python_bin: "/usr/bin/python3"
    files_dir: "{{ playbook_dir }}/files"
    rendered_prometheus_secret_path: "{{ files_dir }}/prometheus-dashboard-secret.yaml"
    rendered_grafana_secret_path: "{{ files_dir }}/grafana-dashboard-secret.yaml"
    sealed_prometheus_secret_path: "{{ files_dir }}/prometheus-dashboard-sealed.yaml"
    sealed_grafana_secret_path: "{{ files_dir }}/grafana-dashboard-sealed.yaml"
    traefik_namespace: "default" # Asegúrate de configurar este namespace de manera correcta

  tasks:
    # 📋 Verificar si kubeseal está instalado
    - name: Verificar si kubeseal está instalado
      stat:
        path: "{{ kubeseal_path }}"
      register: kubeseal_check

    - name: Abortamos si kubeseal no está instalado
      fail:
        msg: "❌ kubeseal no está instalado en la ruta {{ kubeseal_path }}. Por favor, instálalo."
      when: not kubeseal_check.stat.exists

    # 📋 Verificar si kubectl está instalado
    - name: Verificar si kubectl está instalado
      stat:
        path: "{{ kubectl_path }}"
      register: kubectl_check

    - name: Abortamos si kubectl no está instalado
      fail:
        msg: "❌ kubectl no está instalado en la ruta {{ kubectl_path }}. Por favor, instálalo."
      when: not kubectl_check.stat.exists

    # 📁 Crear directorio para almacenar los secrets si no existe
    - name: Crear directorio para almacenar los secrets si no existe
      file:
        path: "{{ files_dir }}"
        state: directory
        mode: "0755"

    # 🔐 Generar hash htpasswd para Prometheus
    - name: Generar hash htpasswd para Prometheus
      command: >
        {{ python_bin }} -c "import crypt; print('{{ prometheus_auth_user }}:' + crypt.crypt('{{ prometheus_auth_pass }}', crypt.mksalt(crypt.METHOD_MD5)))"
      register: prometheus_htpasswd_output
      changed_when: false

    # 🔐 Generar hash htpasswd para Grafana
    - name: Generar hash htpasswd para Grafana
      command: >
        {{ python_bin }} -c "import crypt; print('{{ grafana_auth_user }}:' + crypt.crypt('{{ grafana_auth_pass }}', crypt.mksalt(crypt.METHOD_MD5)))"
      register: grafana_htpasswd_output
      changed_when: false

    # 📄 Renderizar plantilla de Secret YAML para Prometheus (plano)
    - name: Renderizar plantilla de Secret YAML para Prometheus (plano)
      template:
        src: ../templates/secrets/prometheus-dashboard-secret.yaml.j2
        dest: "{{ rendered_prometheus_secret_path }}"
      vars:
        prometheus_basic_auth: "{{ prometheus_htpasswd_output.stdout }}"

    # 📄 Renderizar plantilla de Secret YAML para Grafana (plano)
    - name: Renderizar plantilla de Secret YAML para Grafana (plano)
      template:
        src: ../templates/secrets/grafana-dashboard-secret.yaml.j2
        dest: "{{ rendered_grafana_secret_path }}"
      vars:
        grafana_basic_auth: "{{ grafana_htpasswd_output.stdout }}"

    # 🔐 Cifrar el Secret de Prometheus con kubeseal
    - name: Cifrar el Secret de Prometheus con kubeseal
      shell: >
        {{ kubeseal_path }}
        --controller-name sealed-secrets-controller
        --controller-namespace {{ traefik_namespace }}
        --format yaml
        < "{{ rendered_prometheus_secret_path }}" > "{{ sealed_prometheus_secret_path }}"
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    # 🔐 Cifrar el Secret de Grafana con kubeseal
    - name: Cifrar el Secret de Grafana con kubeseal
      shell: >
        {{ kubeseal_path }}
        --controller-name sealed-secrets-controller
        --controller-namespace {{ traefik_namespace }}
        --format yaml
        < "{{ rendered_grafana_secret_path }}" > "{{ sealed_grafana_secret_path }}"
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    # Confirmación de cifrado
    - name: Verificar que el Secret cifrado de Prometheus se haya generado
      stat:
        path: "{{ sealed_prometheus_secret_path }}"
      register: sealed_prometheus_secret_check

    - name: Abortamos si el archivo sellado de Prometheus no se generó
      fail:
        msg: "❌ El archivo sellado de Prometheus {{ sealed_prometheus_secret_path }} no se generó correctamente."
      when: not sealed_prometheus_secret_check.stat.exists

    - name: Verificar que el Secret cifrado de Grafana se haya generado
      stat:
        path: "{{ sealed_grafana_secret_path }}"
      register: sealed_grafana_secret_check

    - name: Abortamos si el archivo sellado de Grafana no se generó
      fail:
        msg: "❌ El archivo sellado de Grafana {{ sealed_grafana_secret_path }} no se generó correctamente."
      when: not sealed_grafana_secret_check.stat.exists

    # Mensaje final
    - name: Mensaje final
      debug:
        msg: "✅ Secret de autenticación cifrado correctamente para Prometheus y Grafana."
