# delete_monitoring.yml
---
- name: Eliminar monitoreo completo (Grafana y Prometheus)
  hosts: localhost
  become: yes
  environment:
    KUBECONFIG: "/home/victory/.kube/config"
  
  tasks:
    # 1️⃣ Verificar si el namespace monitoring existe
    - name: 🔍 Verificar si el namespace monitoring existe
      command: /usr/local/bin/kubectl get namespace monitoring
      register: ns_check
      failed_when: false
      changed_when: false

    # 2️⃣ Eliminar namespace si existe
    - name: ❌ Eliminar namespace monitoring
      command: /usr/local/bin/kubectl delete namespace monitoring
      when: ns_check.rc == 0
      register: ns_delete
      failed_when: ns_delete.rc != 0
      changed_when: "'deleted' in ns_delete.stdout"

    - name: ℹ️ Namespace ya eliminado o no existe
      debug:
        msg: "✅ Namespace 'monitoring' ya estaba eliminado."
      when: ns_check.rc != 0

    - name: ⚠️ Error al eliminar namespace
      debug:
        msg: "❌ Error al eliminar el namespace: {{ ns_delete.stderr }}"
      when: ns_check.rc == 0 and ns_delete.rc != 0

    # 3️⃣ Verificar y eliminar PVCs de Grafana y Prometheus
    - name: 🔍 Verificar PVCs de Grafana y Prometheus
      command: /usr/local/bin/kubectl get pvc grafana-pvc prometheus-pvc -n monitoring
      register: pvc_check
      failed_when: false
      changed_when: false

    - name: ❌ Eliminar PVCs de Grafana y Prometheus
      command: /usr/local/bin/kubectl delete pvc grafana-pvc prometheus-pvc -n monitoring
      when: pvc_check.rc == 0
      register: pvc_delete
      failed_when: false
      changed_when: "'deleted' in pvc_delete.stdout"

    - name: ℹ️ PVCs eliminados o no existen
      debug:
        msg: "ℹ️ PVCs eliminados o no existen: {{ pvc_delete.stdout | default('No se encontraron PVCs') }}"

    # 4️⃣ Verificar y eliminar servicios de Prometheus
    - name: 🔍 Verificar servicios de Prometheus
      command: /usr/local/bin/kubectl get service prometheus-server prometheus-alertmanager prometheus-kube-state-metrics prometheus-prometheus-node-exporter prometheus-prometheus-pushgateway -n monitoring
      register: svc_check
      failed_when: false
      changed_when: false

    - name: ❌ Eliminar servicios de Prometheus
      command: >
        /usr/local/bin/kubectl delete service prometheus-server
        prometheus-alertmanager
        prometheus-kube-state-metrics
        prometheus-prometheus-node-exporter
        prometheus-prometheus-pushgateway -n monitoring
      when: svc_check.rc == 0
      register: svc_delete
      failed_when: false
      changed_when: "'deleted' in svc_delete.stdout"

    - name: ℹ️ Servicios eliminados o no existen
      debug:
        msg: "ℹ️ Servicios eliminados o no existen: {{ svc_delete.stdout | default('No se encontraron servicios') }}"

    # 5️⃣ Verificar y eliminar Pods de Grafana y Prometheus
    - name: 🔍 Verificar Pods de Grafana y Prometheus
      command: /usr/local/bin/kubectl get pod grafana-* prometheus-* -n monitoring
      register: pods_check
      failed_when: false
      changed_when: false

    - name: ❌ Eliminar Pods de Grafana y Prometheus
      command: /usr/local/bin/kubectl delete pod -l app in (grafana,prometheus) -n monitoring
      when: pods_check.rc == 0
      register: pods_delete
      failed_when: false
      changed_when: "'deleted' in pods_delete.stdout"

    - name: ℹ️ Pods eliminados o no existen
      debug:
        msg: "ℹ️ Pods eliminados o no existen: {{ pods_delete.stdout | default('No se encontraron pods') }}"

    # 6️⃣ Verificar y eliminar PVCs de Longhorn
    - name: 🔍 Verificar PVCs de Longhorn
      command: /usr/local/bin/kubectl get pvc -l app=longhorn -n monitoring
      register: longhorn_check
      failed_when: false
      changed_when: false

    - name: ❌ Eliminar PVCs de Longhorn con label app=longhorn
      command: /usr/local/bin/kubectl delete pvc -l app=longhorn -n monitoring
      when: longhorn_check.rc == 0
      register: longhorn_pvc_delete
      failed_when: false
      changed_when: "'deleted' in longhorn_pvc_delete.stdout"

    - name: ℹ️ PVCs de Longhorn eliminados o no existen
      debug:
        msg: "ℹ️ PVCs de Longhorn eliminados o no existen: {{ longhorn_pvc_delete.stdout | default('No se encontraron PVCs con label app=longhorn') }}"
