# delete_monitoring.yml
---
- name: Eliminar monitoreo completo (Grafana y Prometheus)
  hosts: localhost
  become: yes
  environment:
    KUBECONFIG: "/home/victory/.kube/config"
  tasks:
    # Eliminar el namespace 'monitoring' si existe
    - name: Eliminar el namespace monitoring si existe
      command: /usr/local/bin/kubectl delete namespace monitoring
      ignore_errors: true
      
    # Eliminar los PVCs de Grafana y Prometheus
    - name: Eliminar los PVCs de Grafana y Prometheus
      command: /usr/local/bin/kubectl delete pvc grafana-pvc prometheus-pvc -n monitoring
      ignore_errors: true

    # Eliminar los servicios de Prometheus
    - name: Eliminar los servicios de Prometheus
      command: /usr/local/bin/kubectl delete service prometheus-server prometheus-alertmanager prometheus-kube-state-metrics prometheus-prometheus-node-exporter prometheus-prometheus-pushgateway -n monitoring
      ignore_errors: true

    # Eliminar los Pods de Grafana y Prometheus
    - name: Eliminar los Pods de Grafana y Prometheus
      command: /usr/local/bin/kubectl delete pod grafana-* prometheus-* -n monitoring
      ignore_errors: true

    # (Opcional) Eliminar Longhorn si se desea eliminar
    - name: Eliminar los recursos Longhorn de monitoreo
      command: /usr/local/bin/kubectl delete pvc -l app=longhorn -n monitoring
      ignore_errors: true
