---
- name: Instalar kubectl en el nodo local
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Descargar kubectl (v1.29.0)
      get_url:
        url: "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verificar versión de kubectl
      command: kubectl version --client
      register: kubectl_out
      ignore_errors: yes

    - name: Mostrar salida de kubectl
      debug:
        msg: "{{ kubectl_out.stdout }}"