# install_monitoring.yml
---
- name: Instalar Prometheus y Grafana si no están instalados
  hosts: localhost
  gather_facts: false
  become: true

  tasks:

    - name: Comprobar si Prometheus ya está instalado
      kubernetes.core.helm:
        kubeconfig: "/home/victory/.kube/config"
        validate_certs: false
        name: prometheus
        state: present
      register: prometheus_installed
      ignore_errors: true

    - name: Comprobar si Grafana ya está instalado
      kubernetes.core.helm:
        kubeconfig: "/home/victory/.kube/config"
        validate_certs: false
        name: grafana
        state: present
      register: grafana_installed
      ignore_errors: true

    - name: Instalar Prometheus vía Helm si no está instalado
      kubernetes.core.helm:
        kubeconfig: "/home/victory/.kube/config"
        validate_certs: false
        name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: monitoring
        create_namespace: false
        values:
          persistence:
            enabled: true
            existingClaim: prometheus-pvc
      when: prometheus_installed is failed

    - name: Instalar Grafana vía Helm si no está instalado
      kubernetes.core.helm:
        kubeconfig: "/home/victory/.kube/config"
        validate_certs: false
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: monitoring
        create_namespace: false
        values:
          persistence:
            enabled: true
            existingClaim: grafana-pvc
          adminPassword: "{{ grafana_admin_password }}"
          service:
            type: ClusterIP
      when: grafana_installed is failed

    - name: Mostrar mensaje de instalación exitosa
      debug:
        msg: "Prometheus y Grafana se han instalado correctamente en el namespace 'monitoring'."