- name: Desplegar stack de monitoreo con Grafana y Prometheus
  hosts: masters
  become: true
  tasks:
    - name: Incluir rol de Prometheus
      include_role:
        name: prometheus

    - name: Incluir rol de Grafana
      include_role:
        name: grafana
