# playbook_monitoring.yml
- name: Desplegar stack de monitoreo con Grafana y Prometheus
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Incluir rol de Prometheus
      include_role:
        name: prometheus

    - name: Incluir rol de Grafana
      include_role:
        name: grafana