---
- name: Eliminar monitoreo completo (Grafana y Prometheus)
  hosts: localhost
  become: yes
  tasks:
    # Eliminar namespace 'monitoring' si existe
    - name: Eliminar el namespace monitoring
      k8s:
        name: monitoring
        state: absent

    # Eliminar los PVCs de Grafana y Prometheus
    - name: Eliminar los PVCs de Grafana y Prometheus
      k8s:
        state: absent
        kind: PersistentVolumeClaim
        name: 
          - grafana-pvc
          - prometheus-pvc
        namespace: monitoring

    # Eliminar el servicio de Prometheus
    - name: Eliminar el servicio de Prometheus
      k8s:
        state: absent
        kind: Service
        name:
          - prometheus-server
          - prometheus-alertmanager
          - prometheus-kube-state-metrics
          - prometheus-prometheus-node-exporter
          - prometheus-prometheus-pushgateway
        namespace: monitoring

    # Eliminar los Pods de Grafana y Prometheus
    - name: Eliminar los Pods de Grafana y Prometheus
      k8s:
        state: absent
        kind: Pod
        name:
          - grafana-84fb65758f-dggvh
          - prometheus-alertmanager-0
          - prometheus-kube-state-metrics-6cf54df84c-26skr
          - prometheus-prometheus-node-exporter-27b5l
          - prometheus-prometheus-node-exporter-52s2j
          - prometheus-prometheus-node-exporter-8g8sd
          - prometheus-prometheus-node-exporter-cf2tk
          - prometheus-prometheus-node-exporter-dl8h5
          - prometheus-prometheus-node-exporter-pmxj6
          - prometheus-prometheus-node-exporter-zq2gc
          - prometheus-prometheus-pushgateway-544579d549-jwppz
          - prometheus-server-86786fd6d8-kfvg9
        namespace: monitoring