---
- name: Eliminar monitoreo completo (Grafana y Prometheus)
  hosts: localhost
  become: yes
  environment:
    KUBECONFIG: "/home/victory/.kube/config"  # Asegúrate de que esta ruta sea correcta
  tasks:

    # Eliminar el namespace 'monitoring' si existe
    - name: Eliminar el namespace monitoring
      command: kubectl delete namespace monitoring

    # Eliminar los PVCs de Grafana y Prometheus
    - name: Eliminar los PVCs de Grafana y Prometheus
      command: kubectl delete pvc grafana-pvc prometheus-pvc -n monitoring

    # Eliminar el servicio de Prometheus
    - name: Eliminar los servicios de Prometheus
      command: kubectl delete service prometheus-server prometheus-alertmanager prometheus-kube-state-metrics prometheus-prometheus-node-exporter prometheus-prometheus-pushgateway -n monitoring

    # Eliminar los Pods de Grafana y Prometheus
    - name: Eliminar los Pods de Grafana y Prometheus
      command: kubectl delete pod grafana-* prometheus-* -n monitoring

    # (Opcional) Eliminar Longhorn si se desea eliminar
    - name: Eliminar el namespace longhorn
      command: kubectl delete namespace longhorn-system