---
# site.yml - Playbook maestro para el stack de monitoreo
# Mejora: Eliminamos referencias a roles no incluidos (como storage_setup)
# y enfocamos este playbook a instalar Prometheus + Grafana sobre Kubernetes.

- name: 🚀 Desplegar stack de monitoreo con Grafana y Prometheus
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: 🌎 Configurar kubeconfig local
      import_playbook: setup_kubeconfig.yml

    - name: 🔺 Instalar Helm si no está presente
      import_playbook: install_helm.yml

    - name: 🌌 Desplegar stack de monitoreo (Prometheus + Grafana)
      import_playbook: playbook_monitoring.yml