# site.yml
# 🧩 Playbook maestro para desplegar Prometheus y Grafana en Kubernetes con almacenamiento persistente (Longhorn)

# 0️⃣ Configurar kubeconfig local para acceso al clúster
- import_playbook: setup_kubeconfig.yml

# 1️⃣ Instalar Helm (v3) en el nodo de control
- import_playbook: install_helm.yml

# 2️⃣ Desplegar stack de monitoreo con PVCs Longhorn
- import_playbook: playbook_monitoring.yml