# site.yml
---
- name: 0️⃣ Configurar kubeconfig local para acceder al clúster K3s
  import_playbook: setup_kubeconfig.yml

- name: 1️⃣ Instalar Helm en el nodo controlador
  hosts: localhost
  tasks:
    - name: Verificar si Helm está instalado
      command: helm version --short
      register: helm_installed
      ignore_errors: true

    - name: Instalar Helm si no está instalado
      include_tasks: install_helm.yml
      when: helm_installed.rc != 0

- name: 2️⃣ Desplegar stack de monitoreo con Grafana y Prometheus
  import_playbook: playbook_monitoring.yml