---
# 🧩 Playbook maestro para desplegar el stack de monitoreo completo en Kubernetes
# Incluye: kubectl, kubeconfig, Helm, Prometheus y Grafana con almacenamiento persistente

# 1️⃣ Instalar kubectl en el nodo local
- import_playbook: install_kubectl.yml

# 2️⃣ Configurar kubeconfig para acceder al clúster
- import_playbook: setup_kubeconfig.yml

# 3️⃣ Instalar Helm en el nodo local
- import_playbook: install_helm.yml

# 4️⃣ Desplegar Prometheus y Grafana vía roles reutilizables
- import_playbook: playbook_monitoring.yml