#  uninstall_stack.yml
---
# 🧼 Playbook para eliminar por completo Prometheus + Grafana + namespace + RBAC

- name: 🧼 Eliminar stack de monitoreo (Prometheus + Grafana)
  hosts: controller
  become: true
  gather_facts: false
  vars:
    ns: monitoring
    kubeconfig_path: "/home/victory/.kube/config"
    kubectl_path: "/usr/local/bin/kubectl"
    helm_path: "/usr/local/bin/helm" # Ruta de Helm, si no está en el PATH

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

  tasks:
    - name: 🔍 Verificar si el namespace '{{ ns }}' existe
      command: "{{ kubectl_path }} get namespace {{ ns }}"
      register: ns_check
      failed_when: false
      changed_when: false

    - name: ❌ Desinstalar Prometheus con Helm
      command: "{{ helm_path }} uninstall prometheus -n {{ ns }}"
      when: ns_check.rc == 0
      ignore_errors: true

    - name: ❌ Desinstalar Grafana con Helm
      command: "{{ helm_path }} uninstall grafana -n {{ ns }}"
      when: ns_check.rc == 0
      ignore_errors: true

    - name: 🧽 Eliminar todos los recursos del namespace
      shell: "{{ kubectl_path }} delete pvc,svc,pod,secret,configmap --all -n {{ ns }} --ignore-not-found=true"
      when: ns_check.rc == 0
      ignore_errors: true

    - name: ❌ Eliminar namespace '{{ ns }}'
      command: "{{ kubectl_path }} delete namespace {{ ns }} --ignore-not-found=true"
      when: ns_check.rc == 0
      register: ns_delete
      ignore_errors: true

    - name: 💤 Esperar 5s antes de verificar nuevamente
      pause:
        seconds: 5
      when: ns_check.rc == 0

    - name: 🔁 Comprobar si el namespace aún existe
      command: "{{ kubectl_path }} get namespace {{ ns }}"
      register: ns_still_exists
      failed_when: false
      changed_when: false

    - name: 🛠 Eliminar finalizers si el namespace está colgado
      shell: |
        {{ kubectl_path }} get namespace {{ ns }} -o json \
        | jq 'del(.spec.finalizers)' \
        | {{ kubectl_path }} replace --raw "/api/v1/namespaces/{{ ns }}/finalize" -f -
      when:
        - ns_still_exists.rc == 0
      ignore_errors: true

    - name: ✅ Confirmación final del namespace
      shell: "{{ kubectl_path }} get namespace {{ ns }}"
      register: ns_check_final
      failed_when: false
      changed_when: false

    - name: ✅ Namespace eliminado correctamente
      debug:
        msg: "✅ Namespace '{{ ns }}' eliminado correctamente."
      when: ns_check_final.rc != 0

    - name: ⚠️ El namespace aún persiste
      debug:
        msg: "⚠️ Namespace '{{ ns }}' aún está activo. Revisa si hay CRDs o operadores recreándolo automáticamente."
      when: ns_check_final.rc == 0

    # **Eliminar RBAC relacionados con monitoreo**
    - name: ❌ Eliminar ClusterRole 'system:monitoring'
      command: "{{ kubectl_path }} delete clusterrole system:monitoring --ignore-not-found=true"
      ignore_errors: true

    - name: ❌ Eliminar ClusterRoleBinding 'system:monitoring'
      command: "{{ kubectl_path }} delete clusterrolebinding system:monitoring --ignore-not-found=true"
      ignore_errors: true

    - name: ❌ Eliminar los RoleBindings en el namespace de monitoreo
      shell: "{{ kubectl_path }} get rolebinding -n {{ ns }} -o name | grep monitoring | xargs -I {} {{ kubectl_path }} delete {} -n {{ ns }}"
      ignore_errors: true

    - name: ❌ Eliminar los ClusterRoleBindings en el clúster
      shell: "{{ kubectl_path }} get clusterrolebinding -o name | grep monitoring | xargs -I {} {{ kubectl_path }} delete {}"
      ignore_errors: true

    - name: ❌ Eliminar CRDs relacionadas con monitoreo (si existen)
      shell: |
        {{ kubectl_path }} get crd | grep monitoring | awk '{print $1}' | xargs -n 1 {{ kubectl_path }} delete crd
      ignore_errors: true