# uninstall_stack.yml
---
# 🧼 uninstall_stack.yml
# Desinstalación completa del stack de monitoreo (Prometheus + Grafana) y sus recursos asociados

- name: 🧼 Eliminar stack de monitoreo (Prometheus + Grafana)
  hosts: controller
  become: true
  gather_facts: false
  environment:
    KUBECONFIG: "/home/victory/.kube/config"

  vars:
    namespace: monitoring
    temp_file: /tmp/force_delete_ns.json

  tasks:

    - name: 🔍 Verificar si el namespace '{{ namespace }}' existe
      command: kubectl get namespace {{ namespace }}
      register: ns_check
      failed_when: false
      changed_when: false

    - name: ❌ Desinstalar Prometheus con Helm
      command: helm uninstall prometheus -n {{ namespace }}
      when: ns_check.rc == 0
      failed_when: false
      ignore_errors: true

    - name: ❌ Desinstalar Grafana con Helm
      command: helm uninstall grafana -n {{ namespace }}
      when: ns_check.rc == 0
      failed_when: false
      ignore_errors: true

    - name: 🧹 Eliminar todos los PVCs del namespace
      command: kubectl delete pvc --all -n {{ namespace }}
      when: ns_check.rc == 0
      failed_when: false
      ignore_errors: true

    - name: ❌ Eliminar todos los servicios del namespace
      command: kubectl delete svc --all -n {{ namespace }}
      when: ns_check.rc == 0
      failed_when: false
      ignore_errors: true

    - name: ❌ Eliminar todos los pods del namespace
      command: kubectl delete pod --all -n {{ namespace }}
      when: ns_check.rc == 0
      failed_when: false
      ignore_errors: true

    - name: ❌ Eliminar ConfigMaps y Secrets
      command: kubectl delete secret --all -n {{ namespace }}
      when: ns_check.rc == 0
      failed_when: false
      ignore_errors: true

    - name: ❌ Eliminar namespace '{{ namespace }}'
      command: kubectl delete namespace {{ namespace }}
      when: ns_check.rc == 0
      register: ns_delete
      failed_when: false
      changed_when: ns_delete.rc == 0

    - name: ⏳ Esperar 10 segundos antes de verificar finalizers
      pause:
        seconds: 10
      when: ns_check.rc == 0

    - name: 🛠 Forzar eliminación si namespace sigue colgado (finalizers)
      shell: |
        kubectl get namespace {{ namespace }} -o json | \
        jq 'del(.spec.finalizers)' > {{ temp_file }} && \
        kubectl replace --raw "/api/v1/namespaces/{{ namespace }}/finalize" -f {{ temp_file }}
      when: ns_check.rc == 0
      ignore_errors: true
      register: force_ns_cleanup

    - name: ✅ Confirmación de limpieza completa
      debug:
        msg: "🧽 Stack de monitoreo eliminado correctamente."
      when: ns_check.rc == 0

    - name: ℹ️ El namespace '{{ namespace }}' no existía
      debug:
        msg: "✅ El namespace '{{ namespace }}' no existe o ya fue eliminado."
      when: ns_check.rc != 0