---
#  uninstall_stack.yml
# 🧼 Playbook para eliminar por completo Prometheus + Grafana + namespace + RBAC

- name: 🧼 Eliminar stack de monitoreo (Prometheus + Grafana)
  hosts: controller
  become: true
  gather_facts: false
  vars:
    ns: monitoring
  environment:
    KUBECONFIG: "/home/victory/.kube/config"

  tasks:
    - name: 🔍 Verificar si el namespace '{{ ns }}' existe
      command: kubectl get namespace {{ ns }} --ignore-not-found
      register: ns_check
      failed_when: false
      changed_when: false

    - name: ❌ Desinstalar Prometheus con Helm
      command: helm uninstall prometheus -n {{ ns }}
      when: ns_check.rc == 0
      ignore_errors: true

    - name: ❌ Desinstalar Grafana con Helm
      command: helm uninstall grafana -n {{ ns }}
      when: ns_check.rc == 0
      ignore_errors: true

    - name: 🧽 Eliminar todos los recursos del namespace
      command: kubectl delete all --all -n {{ ns }} --ignore-not-found=true
      when: ns_check.rc == 0
      ignore_errors: true

    - name: ❌ Eliminar namespace '{{ ns }}'
      command: kubectl delete namespace {{ ns }} --ignore-not-found=true
      when: ns_check.rc == 0
      register: ns_delete
      ignore_errors: true

    - name: 💤 Esperar 5s antes de verificar nuevamente
      pause:
        seconds: 5
      when: ns_check.rc == 0

    - name: 🔁 Comprobar si el namespace aún existe
      command: kubectl get namespace {{ ns }} --ignore-not-found
      register: ns_still_exists
      failed_when: false
      changed_when: false

    - name: 🛠 Eliminar finalizers si el namespace está colgado
      shell: |
        kubectl get namespace {{ ns }} -o json | kubectl patch namespace {{ ns }} -p '{"metadata":{"finalizers":[]}}'
      when:
        - ns_still_exists.rc == 0
      ignore_errors: true

    - name: ✅ Confirmación final del namespace
      shell: kubectl get namespace {{ ns }} --ignore-not-found
      register: ns_check_final
      failed_when: false
      changed_when: false

    - name: ✅ Namespace eliminado correctamente
      debug:
        msg: "✅ Namespace '{{ ns }}' eliminado correctamente."
      when: ns_check_final.rc != 0

    - name: ⚠️ El namespace aún persiste
      debug:
        msg: "⚠️ Namespace '{{ ns }}' aún está activo. Revisa si hay CRDs o operadores recreándolo automáticamente."
      when: ns_check_final.rc == 0

    - name: ❌ Eliminar ClusterRole 'system:monitoring'
      command: kubectl delete clusterrole system:monitoring --ignore-not-found=true
      ignore_errors: true

    - name: ❌ Eliminar ClusterRoleBinding 'system:monitoring'
      command: kubectl delete clusterrolebinding system:monitoring --ignore-not-found=true
      ignore_errors: true

    - name: ❌ Eliminar CRDs relacionadas con monitoreo (si existen)
      command: kubectl get crd | grep monitoring | awk '{print $1}' | xargs -I {} kubectl delete crd {}
      ignore_errors: true