- name: Crear namespace para monitoreo
  kubernetes.core.k8s:
    name: "{{ monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Crear PVC de Prometheus
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus-pvc.yaml.j2') }}"

- name: Desplegar Prometheus
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus-deployment.yaml.j2') }}"