- name: Crear namespace monitoring si no existe
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Crear PVC de Grafana
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'grafana-pvc.yaml.j2') }}"

- name: Instalar Grafana vía Helm
  community.kubernetes.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring
    create_namespace: false
    values:
      persistence:
        enabled: true
        existingClaim: grafana-pvc
      adminPassword: "{{ grafana_admin_password }}"
      service:
        type: ClusterIP